name: build-$(Build.BuildId)-date-$(Date:yyyy-MM-dd)
variables:
  solutionProjects: '*.sln'
  testProjects:     '[Tt]est/*/*.csproj'
  publishProjects:  '[Ss]rc/*/*.csproj'
  commonArguments:  -p:BuildId=$(Build.BuildId)
  addConfigurationDebugArguments:   --configuration Debug
  addConfigurationReleseArguments:  --configuration Release
  addCodeCoverageArguments:         --collect "Code Coverage"
  addRuntimeArgumentPrefix:         --runtime
  addPublishArguments:              -p:BuildDefaultTargetFramework=true
  addSelfContainedArguments:        --self-contained
jobs:
- template: azure-pipelines.dotnetcore.jobs.yml
  parameters:
    agentPool:        Hosted VS2017
    runtimeMoniker:   win10-x64
    jobNamePrefix:    windows
    jobDisplayPrefix: 'Windows:'
    condition:        ne(variables['SkipWindowsJobs'], 'true')
    enableCodeCoverage: true
    publishDependencyMode: self-contained

- template: azure-pipelines.dotnetcore.jobs.yml
  parameters:
    agentPool:        Hosted Ubuntu 1604
    runtimeMoniker:   ubuntu.16.04-x64
    jobNamePrefix:    ubuntu
    jobDisplayPrefix: 'Ubuntu:'
    condition:        ne(variables['SkipUbuntuJobs'], 'true')
    enableCodeCoverage: false
    publishDependencyMode: self-contained
    addCommonArguments: -p:NoNetFramework=true

- template: azure-pipelines.dotnetcore.jobs.yml
  parameters:
    agentPool:        Hosted macOS
    runtimeMoniker:   osx-x64
    jobNamePrefix:    macos
    jobDisplayPrefix: 'macOS:'
    condition:        ne(variables['SkipMacOSJobs'], 'true')
    enableCodeCoverage: false
    publishDependencyMode: self-contained
    addCommonArguments: -p:NoNetFramework=true

- template: azure-pipelines.dotnetcore.jobs.yml
  parameters:
    runtimeMoniker:   ''
    jobNamePrefix:    dotnetcore
    jobDisplayPrefix: '.NET Core:'
    condition:        ne(variables['SkipDotnetCoreJobs'], 'true')
    publishDependencyMode: framework
