version: 1
update_configs:
- package_manager: "submodules"
  directory: /
  update_schedule: daily
  default_assignees:
  - fredrikhr
  automerged_updates:
  - match:
      update_type: "all"
- package_manager: "dotnet:nuget"
  directory: /
  update_schedule: live
  default_assignees:
  - fredrikhr
  automerged_updates:
  - match:
      dependency_type:  "production"
      update_type:      "semver:minor"
  - match:
      dependency_type:  "development"
      update_type:      "all"
