version: 1
update_configs:
- package_manager: "dotnet:nuget"
  directory: /
  update_schedule: live
  default_assignees:
  - couven92
- package_manager: "submodules"
  directory: /
  update_schedule: daily
  default_assignees:
  - couven92
