name: $(Date:yyyy-MM-dd)-rev$(Rev:r)
variables:
  commonArguments:              -p:BuildId=$(Build.BuildId)
jobs:
- template: azure-pipelines.dotnetcore.buildJob.yml
  parameters:
    jobIdSuffix:                DebugConfiguration
    jobDisplayName:             Debug Configuration
    condition:                  ne(variables['SkipConfigurationDebug'], 'true')
    addStaticConfigurationArguments:  --configuration Debug
    addVarConfigurationArguments:      ${{ variables.AddCommonArguments }} ${{ variables.AddDebugArguments }}
    arftifactNameSuffix:        debug
- template: azure-pipelines.dotnetcore.buildJob.yml
  parameters:
    jobIdSuffix:                ReleaseConfiguration
    jobDisplayName:             Release Configuration
    condition:                  ne(variables['SkipConfigurationRelease'], 'true')
    addStaticConfigurationArguments:  --configuration Release
    addVarConfigurationArguments:     ${{ variables.AddCommonArguments }} ${{ variables.AddReleaseArguments }}
    arftifactNameSuffix:        release
