name: $(Date:yyyy-MM-dd)-rev$(Rev:r)
jobs:
- job: testRunDebugConfiguration
  displayName: Debug Configuration
  condition:    ne(variables['SkipConfigurationDebug'], 'true')
  steps:
  - template: download-azuredevops-msbuild-logger.yml
  - template: azure-pipelines.dotnetcore.testSteps.yml
    parameters:
      configurationId:            Debug
      addConfigurationArguments:  $(AddDebugArguments)
- job: testRunReleaseConfiguration
  displayName: Release Configuration
  condition:    ne(variables['SkipConfigurationRelease'], 'true')
  steps:
  - template: download-azuredevops-msbuild-logger.yml
  - template: azure-pipelines.dotnetcore.testSteps.yml
    parameters:
      configurationId:            Release
      addConfigurationArguments:  $(AddReleaseArguments)
